### ISSUE TITLE
isEmpty of filtered Iterable<T> consumes the first element

### ISSUE THREAD

**Issue by darvasd** [eclipse/xtext-lib#46] opened 2017-03-22 12:18 UTC
If an `Iterable<T>` created by `IteratorExtensions.toIterable` is filtered (by `IterableExtensions.filter`), the behaviour of the resulting `Iterable` is unexpected. For example, the call of `isEmpty` will consume its first element.

MWE:
```
val list = newArrayList(1, 2, 3, 4);
val iterable = list.iterator.toIterable.filter[it < 4];
println(iterable.isEmpty) // prints false
println(iterable) // prints [2, 3] (!)
```

This also implies the following strange situation, where two consecutive calls of `isEmpty` return different values:
```
val list = newArrayList(1, 2, 3, 4);
val iterable = list.iterator.toIterable.filter[it < 2];
println(iterable.isEmpty) // prints 'false'
println(iterable.isEmpty) // prints 'true' (!)
```

If the filtering is performed before the `toIterable` call, the result is as expected:
```
val list = newArrayList(1, 2, 3, 4);
val iterable = list.iterator.filter[it < 2].toIterable;
println(iterable.isEmpty) // prints 'false'
println(iterable.isEmpty) // prints 'false'
```

If there is no filtering, the result is also as expected:
```
val list = newArrayList(1, 2, 3, 4);
val iterable = list.iterator.toIterable;
println(iterable.isEmpty) // prints 'false'
println(iterable.size) // prints '4'
```

Of course, in the examples above it doesn't make any sense to have `list.iterator.toIterable` considering that `ArrayList` is already an `Iterable`, but the same problem happens with `e.eAllContents.toIterable`.

**Comment by cdietrich** [comment] 2017-03-22 12:22
looks like a duplicate of https://bugs.eclipse.org/bugs/show_bug.cgi?id=407901 which was close wontfix

**Comment by darvasd** [comment] 2017-03-22 12:27
Without having a look at the implementation, I think it is not straightforward to know that `isEmpty` counts as iteration and after calling `isEmpty` I shouldn't call anything else on the `Iterable`. Probably a warning about this could help in the Javadoc of `IteratorExtensions.toIterable`.

**Comment by cdietrich** [comment] 2017-03-22 12:43
yes i thought that was already done before. i am still looking for yet another bug demanding this.

**Closed** 2017-04-07 07:51 UTC
Labels: enhancement
